changelog:
  exclude:
    labels:
      - skip-changelog
      - internal
  categories:
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
    - title: Tests
      labels:
        - test
    - title: CI and Build
      labels:
        - ci
        - build
        - chore
    - title: Other Changes
      labels:
        - '*'
